server {
    listen 80;
    server_name ${SUBDOMAIN}.mlpadigital.com;

    root /var/www/${SUBDOMAIN};
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Optional: logic for proxying if the store is a Node app
    # location / {
    #    proxy_pass http://127.0.0.1:4000;
    #    proxy_set_header Host $host;
    # }
}
